// ==========================================
// FORKCAST - SHARED DATA (recipes-data.js)
// ==========================================

const RECIPES_DB = {
  // ---- ONION RECIPES ----
  onion: [
    { id: 'on1', title: 'French Onion Soup', category: 'lunch', time: '45m', diet: 'general', img: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600', desc: 'A rich, deep-flavoured classic French onion soup topped with melted cheese.', ingredients: ['4 onions', '2 tbsp butter', '1L beef broth', 'Gruyère cheese', 'Baguette slices'], steps: ['Caramelise onions in butter for 30 mins.', 'Add broth, simmer 10 mins.', 'Ladle into bowls, top with bread & cheese.', 'Broil until cheese is golden.'] },
    { id: 'on2', title: 'Caramelised Onion Tart', category: 'dinner', time: '60m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdxSKH9_ZRi-9q4ebUdtX4Gb5Sv-oEGUcTiQ&s', desc: 'A buttery pastry shell filled with sweet slow-cooked caramelised onions.', ingredients: ['Puff pastry', '4 onions', '50g butter', '100ml cream', '2 eggs'], steps: ['Blind bake pastry shell.', 'Caramelise onions 40 mins.', 'Mix with cream and eggs.', 'Fill shell, bake 25 mins.'] },
    { id: 'on3', title: 'Onion Salad (Laccha Pyaz)', category: 'lunch', time: '10m', diet: 'vegan', img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/07/onion-salad-recipe.jpg', desc: 'Tangy refreshing Indian onion salad with lemon and chaat masala.', ingredients: ['2 red onions', 'Lemon juice', 'Chaat masala', 'Salt', 'Fresh coriander'], steps: ['Slice onions thinly into rings.', 'Soak in cold water 10 mins.', 'Drain and mix with lemon, masala, salt.', 'Garnish with coriander.'] },
    { id: 'on4', title: 'Onion Rice (Vengaya Sadam)', category: 'lunch', time: '25m', diet: 'vegan', img: 'https://www.allrecipes.com/thmb/i_n0s7tUwY3m27rbYgSME2WWn18=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Onion-Rice-2000-6c38221a8ec04c9dabea4868c806c760.jpg', desc: 'South Indian style fragrant onion rice tempered with mustard and curry leaves.', ingredients: ['2 cups rice', '3 onions', 'Mustard seeds', 'Curry leaves', 'Turmeric'], steps: ['Cook rice and set aside.', 'Temper mustard seeds in oil.', 'Add onions and fry till golden.', 'Mix in rice with spices.'] },
  ],

  // ---- PANEER RECIPES ----
  paneer: [
    { id: 'pn1', title: 'Paneer taco cups', category: 'lunch', time: '20m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBGAXs2Z4nTdSCOaRPQw1YQcqzwXx1VF8Tkw&s', desc: 'Mini taco shells filled with spicy paneer and fresh salsa.', video: 'https://www.youtube.com/results?search_query=Paneer+taco+cups', ingredients: ['Mini taco shells', 'Paneer cubes', 'Taco seasoning', 'Salsa', 'Corn'], steps: ['Sauté paneer with taco seasoning.', 'Fill into taco cups.', 'Top with salsa and corn.'] },
    { id: 'pn2', title: 'Corn and paneer stuffed rolls', category: 'lunch', time: '30m', diet: 'vegetarian', img: 'https://spicecravings.com/wp-content/uploads/2020/12/Paneer-kathi-Roll-6.jpg', desc: 'Crispy rolls stuffed with a delicious corn and paneer mixture.', video: 'https://www.youtube.com/results?search_query=Corn+and+paneer+stuffed+rolls', ingredients: ['Bread slices', 'Paneer', 'Sweet corn', 'Onion', 'Spices'], steps: ['Flatten bread slices with a rolling pin.', 'Fill with corn and paneer mix, roll tightly.', 'Shallow fry until crispy all around.'] },
    { id: 'pn3', title: 'Chilli paneer rice bowl', category: 'dinner', time: '30m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRW06314u_HoZIAhdoihexG9GW_lcMr07dtOA&s', desc: 'A complete meal with spicy chilli paneer over fragrant rice.', video: 'https://www.youtube.com/results?search_query=Chilli+paneer+rice+bowl', ingredients: ['Basmati rice', 'Paneer', 'Capsicum', 'Soy sauce', 'Chilli sauce'], steps: ['Cook rice and set aside.', 'Prepare chilli paneer with veggies and sauces.', 'Serve paneer over a bed of hot rice.'] },
    { id: 'pn4', title: 'Paneer Tikka', category: 'lunch', time: '25m', diet: 'vegetarian', img: 'https://www.cookwithkushi.com/wp-content/uploads/2023/02/tandoori_paneer_tikka_restaurant_style.jpg', desc: 'Smoky grilled paneer tikka marinated in yoghurt and spices.', ingredients: ['400g paneer', 'Yoghurt', 'Tandoori masala', 'Bell peppers', 'Lemon'], steps: ['Marinate paneer in spiced yoghurt 1hr.', 'Thread on skewers with peppers.', 'Grill or broil 15 mins.', 'Serve with mint chutney.'] },
    { id: 'pn5', title: 'Kadai Paneer', category: 'dinner', time: '35m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDZuXsR64zlMC-0byxhDjNjInuQymLvUR36w&s', desc: 'Bold kadai spiced paneer cooked with onion and capsicum.', ingredients: ['300g paneer', 'Capsicum', 'Onion', 'Tomatoes', 'Kadai masala'], steps: ['Roast and grind whole spices.', 'Cook onion-tomato masala.', 'Add capsicum and paneer.', 'Toss with fresh kadai masala.'] },
    { id: 'pn6', title: 'Shahi Paneer', category: 'dinner', time: '45m', diet: 'vegetarian', img: 'https://static.toiimg.com/photo/52446409.cms', desc: 'Royal Mughlai-style paneer in a rich cashew-cream gravy.', ingredients: ['300g paneer', 'Cashews', 'Cream', 'Cardamom', 'Saffron'], steps: ['Soak cashews, blend to paste.', 'Make onion-cashew gravy.', 'Add cream and paneer.', 'Garnish with saffron milk.'] },
    { id: 'pn7', title: 'Paneer Paratha', category: 'breakfast', time: '25m', diet: 'vegetarian', img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/04/paneer-paratha-recipe.jpg', desc: 'Whole wheat flatbread stuffed with spiced crumbled paneer.', ingredients: ['Wheat flour', 'Paneer', 'Green chillies', 'Coriander', 'Ghee'], steps: ['Mix crumbled paneer with spices.', 'Stuff into dough and roll flat.', 'Cook on a tawa with ghee.'] },
    { id: 'pn8', title: 'Palak Paneer', category: 'dinner', time: '30m', diet: 'vegetarian', img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2020/06/palak-paneer-recipe-500x375.jpg', desc: 'Classic Indian dish of paneer in a smooth, spiced spinach gravy.', ingredients: ['Spinach', 'Paneer', 'Cream', 'Garlic', 'Garam masala'], steps: ['Blanch and blend spinach.', 'Sauté garlic and spices, add spinach puree.', 'Toss in paneer cubes and cream.'] },
    { id: 'pn9', title: 'Paneer Butter Masala', category: 'dinner', time: '30m', diet: 'vegetarian', img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2014/11/paneer-butter-masala-recipe-2.jpg', desc: 'Rich, creamy tomato-butter sauce filled with soft cubes of paneer.', ingredients: ['Paneer', 'Butter', 'Cream', 'Tomatoes', 'Onions', 'Spices'], steps: ['Sauté onions and spices.', 'Add tomato puree and cook.', 'Add butter, cream, and paneer cubes.', 'Simmer for 5 mins.'] }
  ],
  // ---- POTATO RECIPES ----
  potato: [
    { id: 'pt1', title: 'Potato cheese pancakes', category: 'breakfast', time: '20m', diet: 'vegetarian', img: 'https://i.ytimg.com/vi/tnMzIbXeIk4/sddefault.jpg', desc: 'Savory pancakes made with grated potatoes and cheese.', video: 'https://www.youtube.com/results?search_query=Potato+cheese+pancakes', ingredients: ['Potatoes', 'Cheese', 'Eggs', 'Flour', 'Herbs'], steps: ['Grate potatoes and squeeze out water.', 'Mix with cheese, eggs, and flour.', 'Fry large spoonfuls until golden on both sides.'] },
    { id: 'pt2', title: 'Potato pizza', category: 'dinner', time: '35m', diet: 'vegetarian', img: 'https://au.gozney.com/cdn/shop/articles/Potato_Pizza_Tom___Tom_Straker_008e6411-6876-428d-9990-929b2968277a.jpg?v=1743108699', desc: 'An Italian classic with thinly sliced potatoes and rosemary.', video: 'https://www.youtube.com/results?search_query=Potato+pizza', ingredients: ['Pizza base', 'Potatoes', 'Rosemary', 'Mozzarella', 'Garlic'], steps: ['Parboil potato slices.', 'Top pizza base with cheese and potato slices.', 'Bake until crust is crispy and cheese is bubbly.'] },
    { id: 'pt3', title: 'Crispy potato spirals', category: 'lunch', time: '20m', diet: 'vegan', img: 'https://www.bhg.com/thmb/GEWucH4h9nUVoqpuLz72rAqNQLM=/1500x0/filters:no_upscale():strip_icc()/potato-tornadoes-01-hero-351066815c9849c0847ca5cd40e60647.jpg', desc: 'Fun spiral-cut potatoes fried to a perfect crisp.', video: 'https://www.youtube.com/results?search_query=Crispy+potato+spirals', ingredients: ['Large potatoes', 'Corn flour', 'Spices', 'Oil'], steps: ['Spiralize potatoes using a tool.', 'Coat with seasoned corn flour.', 'Deep fry until golden and crispy.'] },
    { id: 'pt4', title: 'Aloo Gobi', category: 'lunch', time: '25m', diet: 'vegan', img: 'https://veenaazmanov.com/wp-content/uploads/2012/10/Aloo-Gobi-Indian-Cauliflower-with-Potates24-500x375.jpg', desc: 'Classic dry Indian sabzi of potatoes and cauliflower with aromatic spices.', ingredients: ['3 potatoes', '1 cauliflower', 'Cumin', 'Turmeric', 'Dry mango powder'], steps: ['Parboil potato and cauliflower.', 'Temper cumin in oil.', 'Add vegetables and all spices.', 'Cook dry on medium heat.'] },
    { id: 'pt5', title: 'Aloo Paratha', category: 'breakfast', time: '30m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx3RJgImzZgMSQSe871cXQxnje-Zg6MI9-Mw&s', desc: 'Whole wheat flatbread stuffed with spiced mashed potato filling.', ingredients: ['Wheat flour', '4 potatoes', 'Green chillies', 'Coriander', 'Ghee'], steps: ['Mash boiled potatoes with spices.', 'Stuff into wheat dough ball.', 'Roll flat and cook on tawa.', 'Serve with butter and pickle.'] },
    { id: 'pt6', title: 'French Fries', category: 'lunch', time: '20m', diet: 'vegan', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYssojePnhY7kKuiqk6Z9EA0dmrXVoQe4DHg&s', desc: 'Golden crispy double-fried fries seasoned with sea salt.', ingredients: ['4 large potatoes', 'Oil for frying', 'Sea salt', 'Paprika'], steps: ['Cut potatoes into matchsticks.', 'Soak in cold water 30 mins.', 'First fry at 150°C for 5 mins.', 'Second fry at 190°C until golden.'] },
    { id: 'pt7', title: 'Aloo Sabzi', category: 'dinner', time: '20m', diet: 'vegan', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5YiLOUGHTOHzDwqZvfs6Jz4tsGcCqCCtgqg&s', desc: 'Simple and comforting North Indian potato curry spiced with cumin.', ingredients: ['3 potatoes', '1 onion', '2 tomatoes', 'Cumin', 'Turmeric', 'Coriander powder'], steps: ['Heat oil and add cumin seeds.', 'Sauté onions until translucent.', 'Add tomatoes and spices, cook until soft.', 'Add cubed potatoes and water, simmer until tender.'] },
    { id: 'pt8', title: 'Potato Corn Salad', category: 'lunch', time: '15m', diet: 'vegan', img: 'https://keviniscooking.com/wp-content/uploads/2018/08/Sweet-Potato-and-Corn-Salad-square.jpg', desc: 'A colorful and refreshing salad combining tender potatoes and sweet corn kernels with a light vinaigrette.', ingredients: ['3 medium potatoes', '1 cup sweet corn kernels (fresh or frozen)', '1/4 cup chopped red onion', '2 tbsp chopped fresh cilantro or parsley', 'Dressing: 2 tbsp olive oil, 1 tbsp lemon juice, salt, pepper'], steps: ['Boil or microwave potatoes until tender, then cool and cube.', 'If using frozen corn, blanch for 2-3 minutes, then cool.', 'In a large bowl, combine cubed potatoes, corn kernels, red onion, and cilantro/parsley.', 'Whisk together olive oil, lemon juice, salt, and pepper for the dressing.', 'Pour dressing over the salad and toss gently to coat.'] },
  ],
  // ---- TOMATO RECIPES ----
  tomato: [
    { id: 'tm1', title: 'Tomato Soup', category: 'lunch', time: '20m', diet: 'vegan', img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/11/tomato-soup-recipe-500x375.jpg', desc: 'Silky smooth roasted tomato soup with fresh basil.', ingredients: ['6 tomatoes', 'Onion', 'Garlic', 'Basil', 'Cream'], steps: ['Roast tomatoes and garlic.', 'Blend with broth.', 'Strain for smooth texture.', 'Finish with cream and basil.'] },
    { id: 'tm2', title: 'Tomato Bruschetta', category: 'breakfast', time: '10m', diet: 'vegan', img: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=600', desc: 'Crispy bread topped with fresh tomato, garlic and basil.', ingredients: ['Baguette', '4 tomatoes', 'Garlic cloves', 'Fresh basil', 'Olive oil'], steps: ['Toast bread slices.', 'Mix diced tomatoes with basil.', 'Rub bread with garlic.', 'Top with tomato mixture.'] },
    { id: 'tm3', title: 'Shakshuka', category: 'breakfast', time: '25m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4EZBZPQqTCNf97zvuD0ie4VEyTi7CjcEW7Q&s', desc: 'Eggs poached in a spiced tomato and pepper sauce.', ingredients: ['6 tomatoes', '4 eggs', 'Bell pepper', 'Cumin', 'Feta'], steps: ['Make spiced tomato sauce.', 'Make wells in sauce.', 'Crack eggs into wells.', 'Cover and cook 8 mins.'] },
    { id: 'tm4', title: 'Tomato Rice', category: 'lunch', time: '20m', diet: 'vegan', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdnlE6sYkRjCKp9djOIhOR_FPE_7PO6qisBA&s', desc: 'South Indian tangy tomato rice packed with flavour.', ingredients: ['2 cups rice', '5 tomatoes', 'Mustard seeds', 'Chillies', 'Curry leaves'], steps: ['Cook rice separately.', 'Prepare tomato masala.', 'Mix with rice.', 'Temper with mustard seeds.'] },
  ],

  // ---- SPINACH RECIPES ----
  spinach: [
    { id: 'sp1', title: 'Spinach Smoothie', category: 'breakfast', time: '5m', diet: 'vegan', img: 'https://www.eatloveeats.com/wp-content/uploads/2022/05/Banana-Spinach-Smoothie-Featured.jpg', desc: 'Energising green smoothie with spinach, banana and mango.', ingredients: ['2 cups spinach', '1 banana', '1 cup mango', 'Almond milk', 'Chia seeds'], steps: ['Add all ingredients to blender.', 'Blend until smooth.', 'Taste and adjust sweetness.', 'Serve immediately.'] },
    { id: 'sp2', title: 'Spinach Pasta', category: 'dinner', time: '25m', diet: 'vegetarian', img: 'https://thecozycook.com/wp-content/uploads/2021/08/Spinach-Pasta-3-scaled.jpg', desc: 'Creamy garlic spinach pasta that comes together in minutes.', ingredients: ['Pasta', '2 cups spinach', 'Garlic', 'Cream', 'Parmesan'], steps: ['Cook pasta al dente.', 'Sauté garlic in olive oil.', 'Wilt spinach, add cream.', 'Toss pasta in sauce.'] },
    { id: 'sp3', title: 'Saag Aloo', category: 'dinner', time: '30m', diet: 'vegan', img: 'https://everydaynourishingfoods.com/wp-content/uploads/2025/03/saag-aloo-featured-image.jpeg', desc: 'Hearty Indian potato and spinach curry with warming spices.', ingredients: ['300g spinach', '4 potatoes', 'Onion', 'Ginger-garlic', 'Garam masala'], steps: ['Blanch and chop spinach.', 'Boil and cube potatoes.', 'Make onion-masala base.', 'Combine and simmer.'] },
  ],

  // ---- CHICKEN RECIPES ----
  chicken: [
    { id: 'ch1', title: 'Butter Chicken', category: 'dinner', time: '50m', diet: 'non-veg', img: 'https://nickskitchen.com/wp-content/uploads/2025/08/NK_Butter-Ckn_1-scaled.jpg', desc: 'The iconic creamy tomato butter chicken loved worldwide with a rich, velvety gravy.', ingredients: ['500g chicken', 'Butter', 'Cream', 'Tomatoes', 'Spices'], steps: ['Marinate and grill chicken.', 'Make tomato-cream sauce with plenty of butter.', 'Simmer chicken in the rich sauce.', 'Finish with cream and a dollop of butter.'] },
    { id: 'ch2', title: 'Chicken Salad', category: 'lunch', time: '15m', diet: 'non-veg', img: 'https://www.giverecipe.com/wp-content/uploads/2019/05/Turkish-Chicken-Salad-Featured-2.jpg', desc: 'Light grilled chicken salad with avocado and lemon dressing.', ingredients: ['Chicken breast', 'Mixed greens', 'Avocado', 'Cherry tomatoes', 'Lemon'], steps: ['Grill seasoned chicken breast.', 'Slice when cooled.', 'Assemble salad with greens.', 'Drizzle with lemon dressing.'] },
    { id: 'ch3', title: 'Chicken Biryani', category: 'dinner', time: '75m', diet: 'non-veg', img: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600', desc: 'Royal aromatic layered biryani with fragrant long-grain basmati rice and tender spiced chicken.', ingredients: ['500g chicken', '2 cups Basmati rice', 'Fried onions', 'Saffron', 'Biryani masala', 'Whole spices'], steps: ['Marinate chicken in spices and yogurt.', 'Parboil the basmati rice with whole spices.', 'Layer the chicken and rice with fried onions and saffron.', 'Dum cook on low heat for 25-30 minutes.'] },
    { id: 'ch4', title: 'Garlic butter chicken with veggies', category: 'dinner', time: '35m', diet: 'non-veg', img: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&sig=gb', desc: 'Tender chicken and veggies sautéed in a rich garlic butter sauce.', video: 'https://www.youtube.com/results?search_query=Garlic+butter+chicken+with+veggies', ingredients: ['Chicken breast', 'Butter', 'Garlic', 'Broccoli', 'Carrots'], steps: ['Sauté chicken until brown.', 'Add garlic, butter, and veggies.', 'Cook until veggies are tender.'] },
    { id: 'ch5', title: 'Chicken tacos', category: 'lunch', time: '25m', diet: 'non-veg', img: 'https://static01.nyt.com/images/2025/05/14/multimedia/kf-easy-chicken-tacos-gwfh/kf-easy-chicken-tacos-gwfh-mediumSquareAt3X.jpg', desc: 'Zesty chicken tacos with fresh toppings and salsa.', video: 'https://www.youtube.com/results?search_query=Chicken+tacos', ingredients: ['Chicken', 'Taco shells', 'Lettuce', 'Salsa', 'Cheese'], steps: ['Season and cook chicken, then shred.', 'Fill shells with chicken and toppings.'] },
    { id: 'ch6', title: 'Chicken lettuce wraps', category: 'lunch', time: '20m', diet: 'non-veg', img: 'https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2FPhoto%2FRecipes%2F2024-05-chicken-lettuce-wraps%2Fchicken-lettuce-wraps-315', desc: 'Healthy and light chicken wraps using fresh lettuce leaves.', video: 'https://www.youtube.com/results?search_query=Chicken+lettuce+wraps', ingredients: ['Minced chicken', 'Lettuce', 'Soy sauce', 'Ginger', 'Garlic'], steps: ['Sauté chicken with aromatics and soy sauce.', 'Spoon into lettuce leaves and serve.'] },
    { id: 'ch7', title: 'Chicken egg fried rice', category: 'dinner', time: '25m', diet: 'non-veg', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTD4w4stC4jfXdtbqdR-6huCiSKfBwYDxpnkw&s', desc: 'Classic fried rice with chicken, eggs, and garden vegetables.', video: 'https://www.youtube.com/results?search_query=Chicken+egg+fried+rice', ingredients: ['Rice', 'Chicken', 'Egg', 'Soy sauce', 'Peas', 'Carrots'], steps: ['Scramble eggs and set aside.', 'Fry chicken and veggies, add rice and soy sauce.', 'Mix in eggs and serve.'] }
  ],

  // ---- APPLE RECIPES ----
  apple: [
    { id: 'ap1', title: 'Apple Pie', category: 'dinner', time: '60m', diet: 'vegetarian', img: 'https://recipe30.com/wp-content/uploads/2020/11/Apple-pie.jpg', desc: 'Classic golden-crusted apple pie with cinnamon filling.', ingredients: ['6 apples', 'Pastry dough', 'Sugar', 'Cinnamon', 'Butter'], steps: ['Make pastry dough.', 'Fill with spiced apples.', 'Top with pastry lid.', 'Bake 45 mins at 190°C.'] },
    { id: 'ap2', title: 'Apple cinnamon oats bowl', category: 'breakfast', time: '10m', diet: 'vegan', img: 'https://www.thereciperebel.com/wp-content/uploads/2025/04/apple-cinnamon-oatmeal-TRR-1200-nm-18-of-19.jpg', desc: 'Warm creamy oats topped with caramelised cinnamon apples.', ingredients: ['1 cup oats', '2 apples', 'Almond milk', 'Cinnamon', 'Maple syrup'], steps: ['Cook oats in almond milk.', 'Sauté diced apple with cinnamon.', 'Top oats with apple.', 'Drizzle maple syrup.'] },
    { id: 'ap3', title: 'Apple Walnut Salad', category: 'lunch', time: '10m', diet: 'vegan', img: 'https://www.wellplated.com/wp-content/uploads/2020/11/Apple-Salad-with-Endive-and-Arugula.jpg', desc: 'Crisp apple with walnuts and greens in a honey vinaigrette.', ingredients: ['2 apples', 'Walnuts', 'Baby spinach', 'Feta', 'Honey vinaigrette'], steps: ['Slice apple thinly.', 'Toast walnuts lightly.', 'Assemble salad.', 'Dress with honey vinaigrette.'] },
  ],

  // ---- EGG RECIPES ----
  egg: [
    { id: 'eg1', title: 'Masala Omelette', category: 'breakfast', time: '10m', diet: 'vegetarian', img: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600', desc: 'Spicy Indian-style omelette with onion, chilli and coriander.', ingredients: ['3 eggs', 'Onion', 'Green chilli', 'Tomato', 'Coriander'], steps: ['Beat eggs with spices.', 'Sauté veggies in pan.', 'Pour egg mixture over.', 'Cook both sides until done.'] },
    { id: 'eg2', title: 'Egg Fried Rice', category: 'lunch', time: '15m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkrILYTPmy6Xs3pd-aLa2fnTD6jDl070kJFg&s', desc: 'Quick takeaway-style egg fried rice with veggies and soy sauce.', ingredients: ['2 cups rice', '4 eggs', 'Soy sauce', 'Spring onions', 'Garlic'], steps: ['Cook and chill rice.', 'Scramble eggs.', 'Fry garlic in wok.', 'Add rice, eggs, soy sauce.'] },
    { id: 'eg3', title: 'Egg and veggies pizza toast', category: 'breakfast', time: '15m', diet: 'vegetarian', img: 'https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_960,w_960//InstamartAssets/Receipes/egg_pizza.webp', desc: 'A quick pizza-style toast with eggs and vegetables.', video: 'https://www.youtube.com/results?search_query=Egg+and+veggies+pizza+toast', ingredients: ['Bread', 'Eggs', 'Peppers', 'Cheese', 'Pizza sauce'], steps: ['Spread pizza sauce on bread.', 'Top with veggies, cracked egg, and cheese.', 'Bake until egg is set.'] },
    { id: 'eg4', title: 'Masala egg wraps', category: 'lunch', time: '20m', diet: 'vegetarian', img: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?w=600&sig=egwr', desc: 'Spicy scrambled eggs wrapped in a warm tortilla.', video: 'https://www.youtube.com/results?search_query=Masala+egg+wraps', ingredients: ['Tortilla', 'Eggs', 'Onions', 'Spices', 'Green chutney'], steps: ['Scramble eggs with onions and spices.', 'Spread chutney on tortilla, fill with eggs, and wrap.'] },
    { id: 'eg5', title: 'Egg sandwich', category: 'breakfast', time: '10m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyW3MtNJss9F-6tt0xozEFSQiEIrSNlRA74w&s', desc: 'Classic egg sandwich with boiled eggs and fresh lettuce.', video: 'https://www.youtube.com/results?search_query=Egg+sandwich', ingredients: ['Bread', 'Boiled eggs', 'Mayo', 'Lettuce'], steps: ['Slices eggs and place on bread with mayo and lettuce.', 'Season with salt and pepper and serve.'] },
    { id: 'eg6', title: 'Veggie omelette', category: 'breakfast', time: '10m', diet: 'vegetarian', img: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600&sig=veg_om', desc: 'A fluffy omelette packed with colorful vegetables.', video: 'https://www.youtube.com/results?search_query=Veggie+omelette', ingredients: ['Eggs', 'Peppers', 'Onion', 'Spinach', 'Cheese'], steps: ['Whisk eggs and pour into a hot pan.', 'Add chopped veggies and cheese.', 'Fold and cook until done.'] },
    { id: 'eg7', title: 'Toast & Eggs', category: 'breakfast', time: '10m', diet: 'non-veg', img: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&sig=te', desc: 'Simple and classic breakfast of toasted bread and eggs.', ingredients: ['Bread', 'Eggs', 'Butter'], steps: ['Toast the bread.', 'Cook eggs as desired (fried, scrambled, or poached).', 'Serve together with butter.'] },
    { id: 'eg8', title: 'Egg Rice', category: 'lunch', time: '20m', diet: 'non-veg', img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/07/egg-rice-recipe.jpg', desc: 'A quick and flavorful meal made with cooked rice and spiced eggs.', ingredients: ['Rice', 'Eggs', 'Onions', 'Soy sauce', 'Spices'], steps: ['Sauté onions and spices.', 'Scramble eggs in the pan.', 'Add cooked rice and soy sauce, toss well.'] }
  ],

  // ---- FRUIT RECIPES ----
  fruit: [
    { id: 'fr1', title: 'Fruit Chaat', category: 'breakfast', time: '10m', diet: 'vegan', img: 'https://www.indianveggiedelight.com/wp-content/uploads/2022/11/fruit-chaat-featured.jpg', desc: 'A vibrant, tangy Indian fruit salad with chaat masala.', ingredients: ['Mixed fruits (apple, banana, pomegranate)', 'Lemon juice', 'Chaat masala', 'Black salt'], steps: ['Chop all fruits into bite-sized pieces.', 'Add lemon juice and chaat masala.', 'Toss well and serve chilled.'] },
    { id: 'fr2', title: 'Healthy Smoothie', category: 'breakfast', time: '5m', diet: 'vegan', img: 'https://www.innermostglobal.com/cdn/shop/articles/High_Protein_Smoothies_2000x.jpg?v=1620143467', desc: 'A thick and creamy blended fruit smoothie.', ingredients: ['1 banana', '1/2 cup berries', '1 cup almond milk', '1 tbsp honey or maple syrup'], steps: ['Combine all ingredients in a blender.', 'Blend on high until smooth.', 'Pour into a glass and enjoy.'] },
    { id: 'fr3', title: 'Watermelon mint coolers', category: 'breakfast', time: '10m', diet: 'vegan', img: 'https://nestle.fitterfly.in/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0FuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--90ece9c2bdc6cb2631b411249c51564cc1ba5615/18623_Pineapple_Watermelon_Mint_Cooler.webp', desc: 'Refreshing summer drink with watermelon and fresh mint.', video: 'https://www.youtube.com/results?search_query=Watermelon+mint+coolers', ingredients: ['Watermelon', 'Mint', 'Lime', 'Ice'], steps: ['Blend watermelon and mint together.', 'Add lime juice and strain.', 'Serve chilled over ice.'] },
    { id: 'fr4', title: 'Frozen fruit popsicle', category: 'breakfast', time: '15m', diet: 'vegan', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWkj3kkF8nrFjbOep4x27PrtNLHr_FRuuXrg&s', desc: 'Healthy fruit popsicles with real fruit chunks.', video: 'https://www.youtube.com/results?search_query=Frozen+fruit+popsicle', ingredients: ['Fruit juice', 'Mixed fruit pieces'], steps: ['Place fruit pieces in popsicle molds.', 'Fill with fruit juice and freeze for 4 hours.'] },
    { id: 'fr5', title: 'Strawberry pancakes', category: 'breakfast', time: '20m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTNzgr8pp46GWUkRYo-1kYTCh19mjzhsO7fA&s', desc: 'Fluffy pancakes topped with fresh strawberries.', video: 'https://www.youtube.com/results?search_query=Strawberry+pancakes', ingredients: ['Strawberries', 'Flour', 'Milk', 'Eggs', 'Maple syrup'], steps: ['Make pancake batter and fry.', 'Top with sliced strawberries and maple syrup.'] },
    { id: 'fr6', title: 'Mixed fruit yogurt bowl', category: 'breakfast', time: '5m', diet: 'vegetarian', img: 'https://i.ytimg.com/vi/545Z4Py8q54/maxresdefault.jpg', desc: 'Creamy yogurt topped with a variety of fresh seasonal fruits.', video: 'https://www.youtube.com/results?search_query=Mixed+fruit+yogurt+bowl', ingredients: ['Yogurt', 'Banana', 'Berries', 'Honey', 'Granola'], steps: ['Place yogurt in a bowl.', 'Top with fruits, granola, and honey.'] }
  ],

  // ---- CORN RECIPES ----
  corn: [
    { id: 'cn1', title: 'Sweet Corn Soup', category: 'dinner', time: '20m', diet: 'vegan', img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/08/sweet-corn-soup-recipe.jpg', desc: 'Comforting Indo-Chinese style sweet corn soup.', ingredients: ['1 cup sweet corn', 'Vegetable broth', 'Spring onions', 'Garlic', 'Cornstarch'], steps: ['Boil broth with corn and veggies.', 'Simmer for 10 mins.', 'Thicken with cornstarch slurry.', 'Serve hot garnished with spring onions.'] },
    { id: 'cn2', title: 'Corn Chaat', category: 'lunch', time: '10m', diet: 'vegan', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJCCuBqfGR56haE_Iul_y9-BKvY-iStWdsbw&s', desc: 'Spicy and tangy Indian street food snack made with sweet corn.', ingredients: ['2 cups boiled corn', 'Onion', 'Tomato', 'Green chilli', 'Chaat masala'], steps: ['Mix warm boiled corn with chopped veggies.', 'Add chaat masala, salt, and lemon juice.', 'Toss well.', 'Garnish with coriander.'] },
    { id: 'cn3', title: 'Corn Fritters', category: 'breakfast', time: '15m', diet: 'vegetarian', img: 'https://cdn.loveandlemons.com/wp-content/uploads/2024/07/corn-fritters.jpg', desc: 'Crispy golden fritters packed with juicy sweet corn kernels.', ingredients: ['2 cups sweet corn', '1/2 cup flour', '1 egg', 'Spring onions', 'Paprika'], steps: ['Mix corn, flour, egg, and spices into a batter.', 'Heat oil in a pan.', 'Drop spoonfuls of batter and fry until golden.', 'Serve with dipping sauce.'] },
    { id: 'cn4', title: 'Crispy corns chaat', category: 'lunch', time: '15m', diet: 'vegan', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIicIfGxKQHeLTzKQecWdIWe04y2qsVKJ-8w&s', desc: 'Deep-fried crispy corn tossed with tangy Indian spices.', video: 'https://www.youtube.com/results?search_query=Crispy+corns+chaat', ingredients: ['Sweet corn', 'Corn flour', 'Chaat masala', 'Lemon', 'Onion'], steps: ['Coat corn in flour and deep fry until crispy.', 'Toss with onions, spices, and lemon juice.', 'Serve immediately.'] },
    { id: 'cn5', title: 'Creamy corn cups', category: 'breakfast', time: '10m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLh-yPDpQ2St3zlf71zbghJJbN10z6eWoVqA&s', desc: 'Sweet corn in a rich, buttery cream sauce served in cups.', video: 'https://www.youtube.com/results?search_query=Creamy+corn+cups', ingredients: ['Corn kernels', 'Butter', 'Cream', 'Cheese', 'Small cups'], steps: ['Simmer corn in cream and butter.', 'Thicken with cheese.', 'Spoon into cups and serve.'] },
    { id: 'cn6', title: 'Corn cheese bombs', category: 'lunch', time: '25m', diet: 'vegetarian', img: 'https://s3-ap-south-1.amazonaws.com/betterbutterbucket-silver/chavi-gupta20181004204728357.jpeg', desc: 'Molten cheese and corn filled potato balls.', video: 'https://www.youtube.com/results?search_query=Corn+cheese+bombs', ingredients: ['Sweet corn', 'Cheese cubes', 'Mashed potatoes', 'Breadcrumbs'], steps: ['Mix corn with mashed potatoes.', 'Insert cheese cube into potato balls.', 'Roll in breadcrumbs and deep fry.'] }
  ],

  // ---- BROCCOLI RECIPES ----
  broccoli: [
    { id: 'br1', title: 'Paneer stuffed broccoli cutlets', category: 'lunch', time: '30m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSugT-k2msb4j32voD5xzmfhKFXFloAxST78A&s', desc: 'Crispy broccoli cutlets with a rich paneer filling.', video: 'https://www.youtube.com/results?search_query=Paneer+stuffed+broccoli+cutlets', ingredients: ['1 head broccoli', '200g paneer', 'Breadcrumbs', 'Ginger-garlic paste', 'Spices'], steps: ['Steam and mash broccoli.', 'Stuff with spiced crumbled paneer.', 'Shape into cutlets, coat with breadcrumbs.', 'Shallow fry until golden brown.'] },
    { id: 'br2', title: 'Cauliflower broccoli Manchurian cups', category: 'dinner', time: '40m', diet: 'vegan', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCcMXtP3aPwhSiLRD7rq0in4pJlTbYar9l-g&s', desc: 'Indo-Chinese style crispy florets served in edible cups.', video: 'https://www.youtube.com/results?search_query=Cauliflower+broccoli+Manchurian+cups', ingredients: ['Broccoli florets', 'Cauliflower florets', 'Soy sauce', 'Chilli sauce', 'Lettuce cups'], steps: ['Batter fry the florets until crispy.', 'Toss in a spicy Manchurian sauce.', 'Serve hot inside fresh lettuce or pastry cups.'] },
    { id: 'br3', title: 'Broccoli potato toast', category: 'breakfast', time: '15m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS94_gn3zfqHCz4AJ5dZRkGF6wpE1HT614KFw&s', desc: 'Healthy morning toast topped with broccoli and mashed potato.', video: 'https://www.youtube.com/results?search_query=Broccoli+potato+toast', ingredients: ['2 slices bread', '1/2 cup broccoli', '1 boiled potato', 'Cheese', 'Pepper'], steps: ['Mash potato with steamed broccoli and spices.', 'Spread on toasted bread.', 'Top with cheese and grill for 2 mins.'] },
    { id: 'br4', title: 'Broccoli corns pasta', category: 'lunch', time: '25m', diet: 'vegetarian', img: 'https://i.imgur.com/fb2gtTS.jpeg', desc: 'Creamy pasta with the goodness of broccoli and sweet corn.', video: 'https://www.youtube.com/results?search_query=Broccoli+corns+pasta', ingredients: ['Pasta', 'Broccoli', 'Sweet corn', 'Cream', 'Garlic', 'Parmesan'], steps: ['Boil pasta and broccoli together.', 'Sauté garlic in butter, add cream and corn.', 'Toss pasta and broccoli in the sauce.'] },
    { id: 'br5', title: 'Broccoli cheese paratha', category: 'breakfast', time: '30m', diet: 'vegetarian', img: 'https://i0.wp.com/vegehomecooking.com/wp-content/uploads/2021/05/BroccoliCheeseParatha16.jpg?resize=1024%2C771&ssl=1', desc: 'Indian flatbread stuffed with finely chopped broccoli and cheese.', video: 'https://www.youtube.com/results?search_query=Broccoli+cheese+paratha', ingredients: ['Wheat flour', '1 cup broccoli', 'Cheese', 'Green chillies', 'Ghee'], steps: ['Grate broccoli and mix with cheese and spices.', 'Stuff into dough balls and roll into parathas.', 'Cook on a tawa with ghee until golden.'] }
  ],

  // ---- VEGGIE RECIPES ----
  veggie: [
    { id: 'vg1', title: 'Veggie nacho skillet', category: 'dinner', time: '20m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGJUVOoali45OZhk965SkZwURuxD9WZAoxNw&s', desc: 'Loaded nachos with beans, corn, and lots of melted cheese.', video: 'https://www.youtube.com/results?search_query=Veggie+nacho+skillet', ingredients: ['Nachos', 'Beans', 'Corn', 'Cheese', 'Salsa'], steps: ['Layer nachos in a skillet.', 'Top with beans, corn, and cheese.', 'Bake until cheese melts and serve with salsa.'] },
    { id: 'vg2', title: 'Rainbow veggies bowl', category: 'lunch', time: '20m', diet: 'vegan', img: 'https://todaysparent.mblycdn.com/tp/resized/2017/07/1600x1200/rainbow-veggie-quinoa-bowl-recipe-1280x960.jpg', desc: 'A colorful and nutritious bowl packed with various vegetables.', video: 'https://www.youtube.com/results?search_query=Rainbow+veggies+bowl', ingredients: ['Quinoa', 'Peppers', 'Purple cabbage', 'Carrot', 'Broccoli'], steps: ['Cook quinoa or rice.', 'Steam or sauté the veggies.', 'Assemble in a bowl with a light dressing.'] },
    { id: 'vg3', title: 'Veggie oats chilla', category: 'breakfast', time: '15m', diet: 'vegan', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKwJHUQHh33jbN7p4p9GzNUJ0YeO5xnESKkg&s', desc: 'Savory oats pancakes loaded with fresh vegetables.', video: 'https://www.youtube.com/results?search_query=Veggie+oats+chilla', ingredients: ['Oats flour', 'Grated carrot', 'Spinach', 'Onion', 'Spices'], steps: ['Make a batter with oats flour and water.', 'Mix in veggies and spices.', 'Cook like a pancake on a non-stick pan.'] },
    { id: 'vg4', title: 'Cabbage cheese toast', category: 'breakfast', time: '10m', diet: 'vegetarian', img: 'https://www.eatingwell.com/thmb/lb9Zll_7ZWB_-pmGPaFuPwkoLIU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/EWL-cabbage-grilled-cheese-Step-04-47-918dc8df2c104f1ca4fb4f5124d73de3.jpg', desc: 'Crispy toast with a crunchy cabbage and cheese topping.', video: 'https://www.youtube.com/results?search_query=Cabbage+cheese+toast', ingredients: ['Bread', 'Cabbage', 'Cheese', 'Butter', 'Pepper'], steps: ['Sauté cabbage with pepper in butter.', 'Place on bread, top with cheese.', 'Toast until cheese is melted.'] },
    { id: 'vg5', title: 'Veg soup', category: 'dinner', time: '25m', diet: 'vegan', img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2019/06/vegetable-soup.jpg', desc: 'Clear vegetable soup that is both light and comforting.', video: 'https://www.youtube.com/results?search_query=Veg+soup', ingredients: ['Carrot', 'Beans', 'Corn', 'Broth', 'Herbs'], steps: ['Boil all veggies in broth.', 'Add salt, pepper, and fresh herbs.', 'Serve hot.'] },
    { id: 'vg6', title: 'Veggie mayo lettuce wraps', category: 'lunch', time: '15m', diet: 'vegetarian', img: 'https://jessicainthekitchen.com/wp-content/uploads/2024/06/Vegan-Lettuce-Wraps8039.jpg', desc: 'Low-carb lettuce wraps filled with crunchy veggies and mayo.', video: 'https://www.youtube.com/results?search_query=Veggie+mayo+lettuce+wraps', ingredients: ['Lettuce leaves', 'Carrot', 'Bell pepper', 'Mayonnaise'], steps: ['Finely chop veggies and mix with mayo.', 'Spoon into large lettuce leaves.', 'Roll and serve chilled.'] },
    { id: 'vg7', title: 'Stuffed onion cups', category: 'lunch', time: '25m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc62QU1JcAjZNiwOd6T-Au03oL0u6I6cinQQ&s', desc: 'Roasted onion shells filled with a spiced vegetable mix.', video: 'https://www.youtube.com/results?search_query=Stuffed+onion+cups', ingredients: ['Large onions', 'Mixed vegetables', 'Cheese', 'Spices'], steps: ['Hollow out the center of the onions.', 'Fill with spiced vegetable mix and cheese.', 'Bake until onions are tender.'] },
    { id: 'vg8', title: 'Carrot cheese pancakes', category: 'breakfast', time: '20m', diet: 'vegetarian', img: 'https://dishingouthealth.com/wp-content/uploads/2026/03/CarrotCakePancakes_Square.jpg', desc: 'Sweet and savory pancakes made with grated carrots and cheese.', video: 'https://www.youtube.com/results?search_query=Carrot+cheese+pancakes', ingredients: ['Carrots', 'Cheese', 'Flour', 'Eggs'], steps: ['Mix grated carrots with flour, cheese, and eggs.', 'Fry in small batches until golden.', 'Serve with honey or yogurt.'] }
  ],

  // ---- MISC / PLANNER RECIPES ----
  misc: [
    { id: 'm1', title: 'Banana Pancakes', category: 'breakfast', time: '15m', diet: 'vegan', img: 'https://www.allrecipes.com/thmb/6x0Lw9L4MEU8INHnK4tXGRV9XWI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20334-banana-pancakes-i-DDMFS-4x3-9f291f03044247d48c9ec26917952402.jpg', desc: 'Fluffy vegan pancakes made with ripe bananas.', ingredients: ['2 ripe bananas', '1 cup oats', '1/2 cup almond milk', 'Cinnamon'], steps: ['Mash bananas and mix with oats, milk, and cinnamon.', 'Cook small scoops on a non-stick pan until golden.'] },
    { id: 'm2', title: 'Vegan Curry', category: 'dinner', time: '30m', diet: 'vegan', img: 'https://www.noracooks.com/wp-content/uploads/2022/08/vegan-curry-8.jpg', desc: 'A rich and creamy coconut-based vegetable curry.', ingredients: ['Mixed veggies', 'Coconut milk', 'Curry powder', 'Tofu', 'Spinach'], steps: ['Sauté veggies and tofu.', 'Add curry powder and coconut milk.', 'Simmer for 15 mins and stir in spinach.'] },
    { id: 'm3', title: 'Smoothie Bowl', category: 'breakfast', time: '10m', diet: 'vegan', img: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600', desc: 'Thick fruit smoothie topped with seeds and nuts.', ingredients: ['Frozen berries', 'Banana', 'Almond milk', 'Granola', 'Chia seeds'], steps: ['Blend fruit and milk into a thick paste.', 'Pour into a bowl and top with granola and seeds.'] },
    { id: 'm4', title: 'Oatmeal', category: 'breakfast', time: '10m', diet: 'vegan', img: 'https://www.veggieinspired.com/wp-content/uploads/2015/05/healthy-oatmeal-berries-featured.jpg', desc: 'Warm and healthy oats with fruit and honey.', ingredients: ['Oats', 'Milk', 'Honey', 'Fruit'], steps: ['Boil oats in milk until soft.', 'Top with fruit and honey.'] },
    { id: 'm5', title: 'Avocado Toast', category: 'breakfast', time: '5m', diet: 'vegan', img: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/avocado-on-toast-96e3158.jpg', desc: 'Simple and delicious avocado on sourdough.', ingredients: ['Bread', 'Avocado', 'Lemon', 'Chilli flakes'], steps: ['Mash avocado with lemon and salt.', 'Spread on toasted bread and sprinkle chilli flakes.'] },
    { id: 'm6', title: 'Fruit Salad', category: 'breakfast', time: '10m', diet: 'vegan', img: 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?w=600', desc: 'Freshly chopped seasonal fruits.', ingredients: ['Apple', 'Banana', 'Orange', 'Grapes'], steps: ['Chop all fruits and mix in a bowl.'] },
    { id: 'm7', title: 'Quinoa Salad', category: 'lunch', time: '20m', diet: 'vegan', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQURUTrEVxhsFuAnFEcj8WjvvSQCmfrFG-YSA&s', desc: 'Light and protein-packed quinoa with veggies.', ingredients: ['Quinoa', 'Cucumber', 'Tomato', 'Lemon', 'Parsley'], steps: ['Cook quinoa and let cool.', 'Mix with chopped veggies and lemon dressing.'] },
    { id: 'm8', title: 'Tofu Rice Bowl', category: 'lunch', time: '25m', diet: 'vegan', img: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600', desc: 'Crispy tofu served over steamed rice and greens.', ingredients: ['Tofu', 'Rice', 'Soy sauce', 'Broccoli'], steps: ['Pan-fry tofu until crispy.', 'Serve over rice with steamed broccoli and soy sauce.'] },
    { id: 'm9', title: 'Veggie Wrap', category: 'lunch', time: '15m', diet: 'vegan', img: 'https://www.plantperks.com/wp-content/uploads/2020/02/IMG_0198-Edit.jpg', desc: 'Healthy vegetable wrap with hummus.', ingredients: ['Tortilla', 'Hummus', 'Cucumber', 'Carrot', 'Spinach'], steps: ['Spread hummus on tortilla.', 'Add veggies and roll tightly.'] },
    { id: 'm10', title: 'Lentil Soup', category: 'dinner', time: '30m', diet: 'vegan', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4F2d2qi-CYgIReRbj40tvTI_XPi2wBS4Bog&s', desc: 'Hearty and warming lentil soup.', ingredients: ['Lentils', 'Carrot', 'Onion', 'Garlic', 'Broth'], steps: ['Sauté onion and garlic.', 'Add lentils and broth, simmer until soft.'] },
    { id: 'm13', title: 'Dal Tadka', category: 'dinner', time: '25m', diet: 'vegan', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtc7CsFor_lFshs_mIqb3uJNaNWkOqJxkQtQ&s', desc: 'Yellow lentils with a smoky tempered spice finish.', ingredients: ['Yellow dal', 'Garlic', 'Cumin', 'Dried red chillies'], steps: ['Boil dal until soft.', 'Prepare tadka with oil, garlic, and cumin.', 'Pour over dal and serve.'] },
    { id: 'm14', title: 'Onion Bhaji', category: 'breakfast', time: '20m', diet: 'vegetarian', img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2025/02/onion-bhaji-recipe.jpg', desc: 'Crispy onion fritters.', ingredients: ['Onions', 'Gram flour', 'Spices'], steps: ['Mix sliced onions with flour and spices.', 'Deep fry in small batches.'] },
    { id: 'm15', title: 'Berry Smoothie', category: 'breakfast', time: '5m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvrkknSo3rm91Z-Xj_5sA0NvIrVw6hTlVCdw&s', desc: 'Refreshing berry and yogurt smoothie.', ingredients: ['Mixed berries', 'Yogurt', 'Honey'], steps: ['Blend all ingredients until smooth.'] },
    { id: 'm16', title: 'Dosa', category: 'breakfast', time: '15m', diet: 'vegetarian', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Rameshwaram_Cafe_Dosa.jpg/1280px-Rameshwaram_Cafe_Dosa.jpg', desc: 'Crispy South Indian rice crepes.', ingredients: ['Dosa batter', 'Oil'], steps: ['Spread batter on a hot tawa.', 'Cook until crispy and serve with chutney.'] },
    { id: 'm17', title: 'Paneer Tikka Sandwich', category: 'lunch', time: '15m', diet: 'vegetarian', img: 'https://i0.wp.com/kalimirchbysmita.com/wp-content/uploads/2018/10/Paneer-Tikka-Sandwich-Insta-02.jpg?resize=1537%2C1024', desc: 'Grilled sandwich with spiced paneer tikka.', ingredients: ['Bread', 'Paneer', 'Tikka masala', 'Bell peppers'], steps: ['Sauté paneer with tikka masala.', 'Fill bread and grill until golden.'] },
    { id: 'm18', title: 'Kadai Paneer Wrap', category: 'lunch', time: '20m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC0Sry9tZpGgJnLlwraEs-Ht98ANhLybNZCQ&s', desc: 'Spicy Kadai paneer in a soft wrap.', ingredients: ['Tortilla', 'Paneer', 'Capsicum', 'Kadai masala'], steps: ['Cook paneer and capsicum in spices.', 'Roll in a tortilla.'] },
    { id: 'm19', title: 'Cheese Pasta', category: 'lunch', time: '20m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzclR8T4SeDwl4jDw1laOOBYkIzSiBe5G89A&s', desc: 'Creamy and cheesy pasta.', ingredients: ['Pasta', 'Cheese sauce', 'Herbs'], steps: ['Boil pasta.', 'Toss in cheese sauce and herbs.'] },
    { id: 'm20', title: 'Veggie Biryani', category: 'lunch', time: '40m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHzR9cdrtxtcQWXfg_8O38Zx0Pgg-KZLKBVQ&s', desc: 'Fragrant rice with vegetables and spices.', ingredients: ['Basmati rice', 'Mixed veggies', 'Biryani masala'], steps: ['Cook rice partially.', 'Layer with spiced veggies.', 'Cook on low heat (dum) for 20 mins.'] },
    { id: 'm21', title: 'Raita Bowl', category: 'lunch', time: '10m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR93Ve0Fm1JXPQogKmEZq2nXhWapzfVxsFdrw&s', desc: 'Cool yogurt with cucumber and spices.', ingredients: ['Yogurt', 'Cucumber', 'Mint', 'Cumin'], steps: ['Mix grated cucumber into yogurt.', 'Add spices and mint.'] },
    { id: 'm22', title: 'Veg Korma', category: 'dinner', time: '30m', diet: 'vegetarian', img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/veg-kurma-vegetable-korma-recipe.jpg', desc: 'Mild and creamy vegetable curry.', ingredients: ['Mixed veggies', 'Cashew paste', 'Cream', 'Spices'], steps: ['Cook veggies in a creamy cashew sauce.'] },
    { id: 'm23', title: 'Poha', category: 'breakfast', time: '15m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpnIwQ79XUuyxcet-fVoPJf2iplEspFK5DJQ&s', desc: 'Flattened rice with peanuts and spices.', ingredients: ['Poha', 'Peanuts', 'Turmeric', 'Lemon'], steps: ['Wash poha.', 'Sauté peanuts and onions.', 'Add poha and turmeric, toss well.'] },
    { id: 'm24', title: 'Rajma Rice', category: 'lunch', time: '40m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrZZYV9Eu13fxu8qXT98ovX6SrG3hGOtpqPw&s', desc: 'Comforting kidney bean curry with steamed rice.', ingredients: ['Rajma', 'Rice', 'Tomato', 'Onion', 'Spices'], steps: ['Pressure cook rajma.', 'Prepare masala and simmer rajma.', 'Serve with rice.'] },
    { id: 'm25', title: 'Dal Chawal', category: 'lunch', time: '30m', diet: 'vegetarian', img: 'https://myheartbeets.com/wp-content/uploads/2020/02/instant-pot-everyday-dal-chawal-500x500.jpg', desc: 'Simple yellow dal served with rice.', ingredients: ['Yellow dal', 'Rice', 'Garlic'], steps: ['Cook dal and rice.', 'Toss dal with garlic tadka.'] },
    { id: 'm26', title: 'Palak Dal', category: 'dinner', time: '25m', diet: 'vegetarian', img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/09/dal-palak-spinach-dal.jpg', desc: 'Lentils cooked with fresh spinach.', ingredients: ['Dal', 'Spinach', 'Garlic'], steps: ['Cook dal with chopped spinach.'] },
    { id: 'm27', title: 'Vegetable Pulao', category: 'dinner', time: '30m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJq0MTUWNF_UF09dUv183INUUggDecvAPcNw&s', desc: 'One-pot spiced rice with vegetables.', ingredients: ['Rice', 'Mixed veggies', 'Spices'], steps: ['Cook rice and veggies together with spices.'] },
    { id: 'm28', title: 'Roti Sabzi', category: 'dinner', time: '30m', diet: 'vegetarian', img: 'https://foodfoodonlyfood.wordpress.com/wp-content/uploads/2016/11/image-1024x1024-1.jpg', desc: 'Hand-rolled flatbread with seasonal vegetable curry.', ingredients: ['Wheat flour', 'Mixed veggies'], steps: ['Make rotis on a tawa.', 'Serve with any veggie curry.'] },
    { id: 'm29', title: 'Pancakes', category: 'breakfast', time: '15m', diet: 'vegetarian', img: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&sig=pc', desc: 'Classic fluffy pancakes.', ingredients: ['Flour', 'Egg', 'Milk', 'Sugar'], steps: ['Mix batter and cook on a griddle.'] },
    { id: 'm30', title: 'Pasta Salad', category: 'lunch', time: '15m', diet: 'vegetarian', img: 'https://ohsweetbasil.com/wp-content/uploads/the-most-flavorful-easy-greek-pasta-recipe-8-Edited.jpg', desc: 'Cold pasta salad with fresh veggies.', ingredients: ['Pasta', 'Cucumber', 'Tomato', 'Olives', 'Dressing'], steps: ['Toss cooked pasta with veggies and dressing.'] },
    { id: 'm31', title: 'Veggie Sandwich', category: 'lunch', time: '10m', diet: 'vegetarian', img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/veg-grilled-sandwich-recipe.jpg', desc: 'Healthy sandwich with cucumber, tomato, and cheese.', ingredients: ['Bread', 'Cucumber', 'Tomato', 'Cheese'], steps: ['Assemble sandwich and serve.'] },
    { id: 'm32', title: 'Chicken Sandwich', category: 'breakfast', time: '15m', diet: 'non-veg', img: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&sig=chsd', desc: 'Grilled chicken breast in a soft sandwich bread.', ingredients: ['Chicken breast', 'Bread', 'Mayo', 'Lettuce'], steps: ['Grill chicken and slice.', 'Assemble sandwich with mayo and lettuce.'] },
    { id: 'm33', title: 'Egg Bhurji', category: 'breakfast', time: '15m', diet: 'non-veg', img: 'https://spicecravings.com/wp-content/uploads/2023/03/Egg-Bhurji-Featured-1-500x500.jpg', desc: 'Spiced Indian scrambled eggs.', ingredients: ['Eggs', 'Onions', 'Tomatoes', 'Green chillies'], steps: ['Sauté onions and chillies.', 'Add tomatoes and spices.', 'Scramble eggs into the mix.'] },
    { id: 'm34', title: 'Bacon & Eggs', category: 'breakfast', time: '15m', diet: 'non-veg', img: 'https://static.toiimg.com/thumb/75680608.cms?imgsize=1875963&width=800&height=800', desc: 'Classic breakfast of crispy bacon and fried eggs.', ingredients: ['Bacon strips', 'Eggs', 'Butter'], steps: ['Fry bacon until crispy.', 'Fry eggs in the same pan.'] },
    { id: 'm35', title: 'Butter Chicken Bowl', category: 'lunch', time: '20m', diet: 'non-veg', img: 'https://nickskitchen.com/wp-content/uploads/2025/08/NK_Butter-Ckn_1-scaled.jpg', desc: 'A convenient single-serving lunch bowl with butter chicken served over fluffy steamed basmati rice.', ingredients: ['Butter chicken curry', 'Steamed Basmati rice', 'Fresh coriander', 'Raita (optional)'], steps: ['Reheat or prepare butter chicken curry.', 'Place a portion of steamed rice in a bowl.', 'Ladle the butter chicken over the rice.', 'Garnish with fresh coriander and serve.'] },
    { id: 'm36', title: 'Keema Paratha', category: 'lunch', time: '35m', diet: 'non-veg', img: 'https://www.licious.in/blog/wp-content/uploads/2022/04/Keema-Paratha_24241-min-1-scaled.jpg', desc: 'Spiced minced meat stuffed in a whole wheat flatbread.', ingredients: ['Wheat flour', 'Minced meat', 'Onions', 'Spices'], steps: ['Cook keema with spices.', 'Stuff into dough and roll into paratha.', 'Cook on a tawa with ghee.'] },
    { id: 'm37', title: 'Fish Tacos', category: 'lunch', time: '25m', diet: 'non-veg', img: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=600&sig=fish', desc: 'Crispy fish fillets in soft tortillas with slaw.', ingredients: ['Fish fillets', 'Tortillas', 'Cabbage slaw', 'Lime'], steps: ['Pan-fry or bake fish.', 'Assemble tacos with slaw and a squeeze of lime.'] },
    { id: 'm38', title: 'Mutton Curry', category: 'dinner', time: '60m', diet: 'non-veg', img: 'https://www.thespruceeats.com/thmb/PEM9oD2Us3ZbYDDeFqEnrPneFxc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/goat-mutton-curry-1957594-hero-01-afaf638173cd47d595c7ad99a018cf01.jpg', desc: 'Slow-cooked tender mutton in a spicy gravy.', ingredients: ['Mutton', 'Onions', 'Tomatoes', 'Yogurt', 'Spices'], steps: ['Sauté onions and spices.', 'Add mutton and brown it.', 'Pressure cook or slow cook with yogurt and water until tender.'] },
    { id: 'm39', title: 'Fish Curry', category: 'dinner', time: '30m', diet: 'non-veg', img: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&sig=fishc', desc: 'Traditional fish curry with coconut and tamarind.', ingredients: ['Fish blocks', 'Coconut milk', 'Tamarind paste', 'Mustard seeds'], steps: ['Temper mustard seeds.', 'Add tamarind and coconut milk.', 'Simmer fish in the gravy until cooked.'] },
    { id: 'm40', title: 'Tandoori Chicken', category: 'dinner', time: '45m', diet: 'non-veg', img: 'https://sinfullyspicy.com/wp-content/uploads/2014/07/1200-by-1200-images-2.jpg', desc: 'Iconic charcoal-grilled chicken marinated in yogurt and a bold tandoori spice blend.', ingredients: ['Chicken leg pieces', 'Yogurt', 'Tandoori masala', 'Ginger-garlic paste', 'Lemon juice'], steps: ['Make deep cuts in chicken and marinate with lemon and salt.', 'Apply the second marinade of spiced yogurt and ginger-garlic paste for 4-6 hours.', 'Grill in a tandoor or oven at high heat until charred.', 'Serve with mint chutney and onion rings.'] },
    { id: 'm41', title: 'Chicken Curry', category: 'dinner', time: '30m', diet: 'non-veg', img: 'https://www.spicebangla.com/wp-content/uploads/2024/10/Chicken-Curry-Recipe0.webp', desc: 'Simple and home-style spicy chicken curry.', ingredients: ['Chicken', 'Onions', 'Tomatoes', 'Curry powder'], steps: ['Sauté onions and spices.', 'Add chicken and cook till brown.', 'Add tomatoes and water, simmer till done.'] },
    { id: 'm42', title: 'Keema Matar', category: 'dinner', time: '35m', diet: 'non-veg', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTO0Qa0BFITcZHMNO2Vb0IUfMP8arHm_aRhkw&s', desc: 'Minced meat cooked with green peas and aromatic spices.', ingredients: ['Minced meat', 'Green peas', 'Onion', 'Spices'], steps: ['Sauté onions and keema.', 'Add peas and spices.', 'Cook on low heat until meat is tender.'] },
    { id: 'm43', title: 'Chicken Tikka Masala', category: 'dinner', time: '50m', diet: 'non-veg', img: 'https://www.licious.in/blog/wp-content/uploads/2020/12/Chicken-Tikka-Masala-min.jpg', desc: 'Grilled chicken pieces in a creamy, spiced tomato sauce.', ingredients: ['Chicken breast', 'Yogurt', 'Tomato puree', 'Cream', 'Spices'], steps: ['Marinate and grill chicken.', 'Prepare creamy tomato sauce.', 'Toss chicken in sauce and simmer.'] },
    { id: 'm44', title: 'Egg Curry', category: 'dinner', time: '30m', diet: 'non-veg', img: 'https://www.whiskaffair.com/wp-content/uploads/2019/03/Chettinad-Egg-Curry-2-3.jpg', desc: 'Boiled eggs in a thick and spicy onion-tomato gravy.', ingredients: ['Boiled eggs', 'Onion', 'Tomato', 'Spices'], steps: ['Fry boiled eggs until golden.', 'Prepare spicy gravy.', 'Add eggs and simmer for 10 mins.'] },
    { id: 'm45', title: 'Prawn Curry', category: 'dinner', time: '25m', diet: 'non-veg', img: 'https://www.whiskaffair.com/wp-content/uploads/2023/02/Shrimp-Masala-2-3.jpg', desc: 'Succulent prawns cooked in a coastal coconut gravy.', ingredients: ['Prawns', 'Coconut milk', 'Tamarind', 'Spices'], steps: ['Cook prawns in a spiced coconut and tamarind base.'] },
    { id: 'm46', title: 'Sausage & Eggs', category: 'breakfast', time: '15m', diet: 'non-veg', img: 'https://static01.nyt.com/images/2024/04/24/multimedia/as-sausage-egg-and-cheeserex-vlcw/as-sausage-egg-and-cheeserex-vlcw-mediumSquareAt3X.jpg', desc: 'Grilled sausages served with sunny-side up eggs.', ingredients: ['Sausages', 'Eggs', 'Toast'], steps: ['Grill sausages until cooked.', 'Fry eggs and serve with toast.'] },
    { id: 'm47', title: 'Ham Sandwich', category: 'breakfast', time: '10m', diet: 'non-veg', img: 'https://www.southernliving.com/thmb/UW4kKKL-_M3WgP7pkL6Pb6lwcgM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Ham_Sandwich_011-1-49227336bc074513aaf8fdbde440eafe.jpg', desc: 'Classic ham and cheese sandwich.', ingredients: ['Ham slices', 'Cheese', 'Bread'], steps: ['Assemble ham and cheese in bread and toast.'] },
    { id: 'm48', title: 'Smoked Salmon Bagel', category: 'breakfast', time: '10m', diet: 'non-veg', img: 'https://www.dontgobaconmyheart.co.uk/wp-content/uploads/2020/04/salmon-cream-cheese-bagel-500x375.jpg', desc: 'Toasted bagel with cream cheese and smoked salmon.', ingredients: ['Bagel', 'Cream cheese', 'Smoked salmon', 'Capers'], steps: ['Toast bagel and spread cream cheese.', 'Top with salmon and capers.'] }
  ],

  // ---- DIET / SPECIAL RECIPES ----
  diet: [
    { id: 'dt1', title: 'Zucchini Noodles', category: 'lunch', time: '15m', diet: 'vegan', img: 'https://www.allrecipes.com/thmb/S2ktDOtLB5yupe7wzKmWdvG00h4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/172398-zucchini-noodles-DDMFS-beauty-4x3-38e8c6f60efd477f8d1a1400f3a825cd.jpg', desc: 'Fresh zucchini spirals tossed with olive oil and garlic.', ingredients: ['2 zucchinis', '2 tbsp olive oil', 'Garlic', 'Cherry tomatoes', 'Parmesan (optional)'], steps: ['Spiralize zucchinis into noodles.', 'Sauté garlic in olive oil.', 'Add noodles and tomatoes, cook for 3-5 mins.', 'Season and serve.'] },
    { id: 'dt2', title: 'Smoked Salmon', category: 'breakfast', time: '5m', diet: 'non-veg', img: 'https://www.vindulge.com/wp-content/uploads/2022/09/Perfect-Smoked-Salmon-Filet.jpg', desc: 'Delicate smoked salmon slices with capers and lemon.', ingredients: ['100g smoked salmon', 'Capers', 'Lemon wedges', 'Fresh dill', 'Cream cheese'], steps: ['Arrange salmon slices on a plate.', 'Top with capers and fresh dill.', 'Serve with lemon wedges and cream cheese.'] },
    { id: 'dt3', title: 'Caesar Salad', category: 'lunch', time: '15m', diet: 'vegetarian', img: 'https://cdn.loveandlemons.com/wp-content/uploads/2024/12/caesar-salad-500x500.jpg', desc: 'Classic romaine lettuce with creamy Caesar dressing and croutons.', ingredients: ['Romaine lettuce', 'Parmesan cheese', 'Croutons', 'Caesar dressing', 'Black pepper'], steps: ['Tear lettuce into bite-sized pieces.', 'Toss with dressing and parmesan.', 'Top with croutons and extra pepper.'] },
    { id: 'dt4', title: 'Cream Cheese Pancakes', category: 'breakfast', time: '15m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQ_koiubjNDcd7jmjJ9bQasHTlYPnOnpXEpA&s', desc: 'Fluffy low-carb pancakes made with cream cheese and eggs.', ingredients: ['100g cream cheese', '2 eggs', '1/2 tsp cinnamon', '1 tsp stevia or honey'], steps: ['Whisk eggs and cream cheese until smooth.', 'Add cinnamon and sweetener.', 'Cook small amounts on a buttered pan until golden.'] },
    { id: 'dt5', title: 'Steak & Broccoli', category: 'dinner', time: '20m', diet: 'non-veg', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdCrd9Myfphm2BEic2KHUT8mu4_0juFkoGNQ&s', desc: 'Juicy grilled steak strips with steamed garlic broccoli.', ingredients: ['200g steak', '1 head broccoli', 'Garlic', 'Butter', 'Soy sauce'], steps: ['Grill or pan-fry steak to desired doneness.', 'Steam broccoli until tender.', 'Toss broccoli with garlic and butter.', 'Slice steak and serve together.'] },
    { id: 'dt6', title: 'Keto Omelette', category: 'breakfast', time: '10m', diet: 'vegetarian', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5kViN4mEvEVEzUbddAhIMX8PQlBLubWda7g&s', desc: 'High-protein omelette with spinach, mushrooms and feta.', ingredients: ['3 eggs', 'Spinach', 'Mushrooms', 'Feta cheese', 'Heavy cream'], steps: ['Whisk eggs with a splash of cream.', 'Sauté mushrooms and spinach.', 'Pour eggs over and top with feta.', 'Fold and serve.'] },
    { id: 'dt7', title: 'Salmon Fillet', category: 'dinner', time: '25m', diet: 'non-veg', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSE2kXgxEL9TDN1euYjxi4IKnG5djSvHPGy3A&s', desc: 'Pan-seared salmon with a crispy skin and lemon butter.', ingredients: ['1 salmon fillet', 'Lemon', 'Butter', 'Asparagus', 'Herbs'], steps: ['Season salmon and sear skin-side down.', 'Flip and cook until opaque.', 'Make a quick lemon butter sauce in the pan.', 'Serve with steamed asparagus.'] },
    { id: 'dt8', title: 'Keto Chicken Curry', category: 'dinner', time: '35m', diet: 'non-veg', img: 'https://sugarfreelondoner.com/wp-content/uploads/2024/05/keto-chicken-curry-1200.jpg', desc: 'Spicy chicken curry made with coconut cream for a keto-friendly meal.', ingredients: ['500g chicken', 'Coconut cream', 'Turmeric', 'Garam masala', 'Ginger', 'Garlic'], steps: ['Sauté aromatics and spices.', 'Add chicken and brown.', 'Pour in coconut cream and simmer until tender.'] },
    { id: 'dt9', title: 'Grilled Paneer', category: 'lunch', time: '15m', diet: 'vegetarian', img: 'https://www.funfoodfrolic.com/wp-content/uploads/2023/09/Grilled-Paneer-Blog.jpg', desc: 'Marinated paneer blocks grilled to perfection.', ingredients: ['200g paneer', 'Yogurt', 'Chili powder', 'Lemon juice', 'Bell peppers'], steps: ['Marinate paneer and peppers in spiced yogurt.', 'Grill on a pan until charred edges appear.', 'Serve hot with lemon.'] },
    { id: 'dt10', title: 'Eggs & Avocado', category: 'breakfast', time: '5m', diet: 'vegetarian', img: 'https://feelgoodfoodie.net/wp-content/uploads/2025/05/Avocado-Toast-10.jpg', desc: 'Simple and nutritious combination of boiled eggs and sliced avocado.', ingredients: ['2 boiled eggs', '1 ripe avocado', 'Chili flakes', 'Salt', 'Lemon'], steps: ['Slice eggs and avocado.', 'Arrange on a plate.', 'Season with salt, chili flakes and lemon.'] },
    { id: 'dt11', title: 'Tuna Bowl', category: 'lunch', time: '10m', diet: 'non-veg', img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdHt2zxQA856ATkP3i3mbtJJXLZaIX_JGpjA&s', desc: 'Protein-packed bowl with canned tuna, greens and a light dressing.', ingredients: ['1 can tuna', 'Mixed greens', 'Cucumber', 'Olive oil', 'Lemon'], steps: ['Mix tuna with a little olive oil and lemon.', 'Place over a bed of greens and cucumber.', 'Top with seeds or pepper.'] },
    { id: 'dt12', title: 'Butter Chicken (no rice)', category: 'dinner', time: '40m', diet: 'non-veg', img: 'https://nickskitchen.com/wp-content/uploads/2025/08/NK_Butter-Ckn_1-scaled.jpg', desc: 'The rich and creamy butter chicken served solo or with cauliflower rice for a low-carb version.', ingredients: ['Butter chicken pieces', 'Rich gravy', 'Cream', 'Fresh coriander'], steps: ['Prepare or reheat butter chicken.', 'Serve in a bowl without rice.', 'Optional: serve with sautéed veggies or cauliflower rice.'] },
    { id: 'dt13', title: 'Greek Yogurt Bowl', category: 'breakfast', time: '5m', diet: 'vegetarian', img: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&sig=gyog', desc: 'Thick and creamy Greek yogurt topped with nuts and a hint of honey.', ingredients: ['1 cup Greek yogurt', 'Walnuts', 'Honey', 'Chia seeds'], steps: ['Place yogurt in a bowl.', 'Top with walnuts and chia seeds.', 'Drizzle with honey and serve.'] }
  ]
};

// Flatten all for "All Recipes" view
const ALL_RECIPES = Object.values(RECIPES_DB).flat();

// Utility: find recipes by ingredient keyword
function searchRecipes(query) {
  if (!query) return [];
  // Clean query: lowercase, trim, and remove trailing punctuation like periods or commas
  const q = query.toLowerCase().trim().replace(/[.,!?;:]+$/, "");

  if (!q) return [];

  // 1. Exact or partial key match (e.g. "broccoli" matches the broccoli category)
  for (let key of Object.keys(RECIPES_DB)) {
    if (q.includes(key) || key.includes(q)) {
      return RECIPES_DB[key];
    }
  }

  // 2. Fallback: search within titles and ingredients for a wider match
  return ALL_RECIPES.filter(r =>
    r.title.toLowerCase().includes(q) ||
    r.ingredients.some(i => i.toLowerCase().includes(q))
  );
}